# Generated by Django 5.1.4 on 2024-12-12 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20, unique=True)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('account_status', models.CharField(choices=[('Активный', 'Активный'), ('Закрытый', 'Закрытый')], default='Активный', max_length=10)),
                ('account_type', models.CharField(choices=[('Текущий', 'Текущий'), ('Сберегательный', 'Сберегательный'), ('Депозитный', 'Депозитный'), ('Валютный', 'Валютный')], default='Текущий', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_date', models.DateField()),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_banking.groupclient')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_banking.client'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_status', models.CharField(choices=[('Активный', 'Активный'), ('Закрытый', 'Закрытый')], default='Активный', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_banking.client')),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_banking.credit')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='currencies',
            field=models.ManyToManyField(related_name='accounts', to='online_banking.currency'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('Пополнение', 'Пополнение'), ('Снятие', 'Снятие'), ('Перевод', 'Перевод')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
